development:
  adapter: postgresql
  database: confs_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: confs_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: confs_production
  pool: 5
  timeout: 5000
